nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs

packageExtensions:
  "nativewind@*":
    peerDependencies:
      react: "*"
      react-native: "*"
      react-native-reanimated: "*"
