nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs

packageExtensions:
  "nativewind@*":
    peerDependencies:
      react: "*"
      react-native: "*"
      react-native-reanimated: "*"

logFilters:
  - code: YN0086
    level: discard
