config:
  aws:region: us-west-2
  limetry-oss:domain: limetry.org
  limetry-oss:apiHostname: api.limetry.org
  limetry-oss:appHostname: app.limetry.org
  limetry-oss:manageRoute53: "false"
  limetry-oss:createHostedZone: "false"
  limetry-oss:manageCloudflare: "true"
  limetry-oss:cloudflareZoneName: limetry.org
  limetry-oss:cloudflareProxied: "true"
  limetry-oss:invalidateOnDeploy: "true"
  limetry-oss:serverArtifactPath: ../server/lambda-bundle
  limetry-oss:webDistPath: ../web/out
  limetry-oss:buildArtifacts: "true"
  limetry-oss:syncWebAssets: "true"
  limetry-oss:githubUrl: https://github.com/limetry/limetry
  limetry-oss:discordUrl: https://discord.gg/limetry
  limetry-oss:contactEmail: hello@limetry.org
  limetry-oss:legalEmail: legal@limetry.org
  limetry-oss:privacyEmail: privacy@limetry.org
  limetry-oss:replayWindowMs: "300000"
  limetry-oss:throttleMaxRequestsPerMinute: "5"
  limetry-oss:defaultAuditMode: minimal
  limetry-oss:auditRetentionDays: "90"
  limetry-oss:databaseUrl:
    secure: AAABAMw1s7XSLO1t+uK3OxuCkmtNtEDNpZt3g1koTbVonwcWdKEBg/08q5GisSedo2fjdYGg5MmCCGGl7aTLvEE5gTwCYzye4wW8IOFUQXy+XeZuKHnx5aUOCS62EXNRslXGxQh4YHB29k262CZIf1z4ksM0mLPiMaN3Ri8VTrlluQPWnTKPaU09XsJ4ZOZofXqZgJc7146BQfIQF6/wpBPY5kRAEe3TrtoSOHl7iyACxmkeau4=
  limetry-oss:jwtSecret:
    secure: AAABALXB5uIXMiOHo9scFJB2yuavjOUnpMCGg46Qdro4uABc2orlxido9/FX7u+cHXi3MD2es8D6DNGVLXF3k9vGj7M4qkrND13ca0b34lKyE+k1lmI28h5gzeyhtnPb
  limetry-oss:bearerToken:
    secure: AAABAGuQiFqrAaq/zsoVdPiGMJPC+rGwkOhOrj+gceQSwZ/VMyNGrYVdpZqXt3NHj1ay+TlySaHXaj3JXVHHLKBgVsNctfHih/NULMeytvT1rdGYayiOA3mhkY0Z0J8H
  limetry-oss:decisionHmacSecret:
    secure: AAABACPTjOr1yBEZ1r7nFz2MHirRFmyILWv+1B73jiqTAlZD7axQUalX/G/pE8MPetWwTEU+X2jzykataLvneYMsXDrCWpRAVURC5/r9e4mZCp7MNFmYUiGIwi427LJL
