/**
 * Browser-based Cloud CLI authentication using PKCE and a loopback callback.
 */

import { createHash, randomBytes } from "node:crypto"
import { createServer, type IncomingMessage, type ServerResponse } from "node:http"

import {
  LIMETRY_CLOUD_APP_ORIGIN,
  resolveLimetryCloudBaseUrl,
} from "@limetry/sdk"
import open from "open"

import {
  type CliConfig,
  getConfig,
  logInfo,
  logSuccess,
  saveConfig,
} from "../../utils/config.js"
import { describeHttpFailure } from "../../utils/errors.js"

const CLIENT_ID = "limetry-cli"
const CALLBACK_PATH = "/oauth/callback"
const CALLBACK_TIMEOUT_MS = 5 * 60 * 1000

type BrowserCallback = {
  code: string
  state: string
}

type CliTokenResponse = {
  accessToken: string
  refreshToken: string
  tokenType: "Bearer"
  expiresIn: number
  baseUrl: string
  user: {
    id: string
    email: string
    tenantId: string
  }
}

/**
 * Provider strategy contract for interactive CLI authentication.
 */
export type CliAuthProvider = {
  id: "clerk"
  login(baseUrl?: string): Promise<CliConfig>
}

/**
 * Opens Cloud sign-in and waits for the authenticated portal to return.
 *
 * @param baseUrl - Cloud BFF API origin.
 * @returns Persisted Cloud CLI configuration.
 */
export async function browserLoginCommand(baseUrl = resolveLimetryCloudBaseUrl()): Promise<CliConfig> {
  const verifier = randomBytes(32).toString("base64url")
  const challenge = createHash("sha256").update(verifier).digest("base64url")
  const state = randomBytes(24).toString("base64url")
  const callback = await startCallbackServer(state)
  const portalUrl = process.env.LIMETRY_CLOUD_APP_URL?.trim() || LIMETRY_CLOUD_APP_ORIGIN
  const authorizeUrl = new URL(`${portalUrl}/cli/authorize`)
  authorizeUrl.searchParams.set("client_id", CLIENT_ID)
  authorizeUrl.searchParams.set("redirect_uri", callback.redirectUri)
  authorizeUrl.searchParams.set("response_type", "code")
  authorizeUrl.searchParams.set("state", state)
  authorizeUrl.searchParams.set("code_challenge", challenge)
  authorizeUrl.searchParams.set("code_challenge_method", "S256")
  authorizeUrl.searchParams.set(
    "scope",
    "policy:evaluate actions:record tokens:manage approvals:manage audit:read policies:write",
  )

  logInfo("Opening Limetry Cloud in your browser...")
  logInfo("Complete sign-in or sign-up there, then approve CLI access.")

  try {
    await open(authorizeUrl.toString())
    const result = await callback.result
    const response = await fetch(`${baseUrl.replace(/\/$/, "")}/v1/auth/cli/token`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        clientId: CLIENT_ID,
        code: result.code,
        codeVerifier: verifier,
        redirectUri: callback.redirectUri,
      }),
    })
    if (!response.ok) {
      throw new Error(describeHttpFailure(response.status, await response.text()))
    }

    const session = (await response.json()) as CliTokenResponse
    const config: CliConfig = {
      ...(getConfig() ?? {}),
      baseUrl: session.baseUrl || baseUrl,
      apiKey: session.accessToken,
      accessToken: session.accessToken,
      refreshToken: session.refreshToken,
      accessTokenExpiresAt: Date.now() + session.expiresIn * 1000,
      authProvider: "cloud",
      tenantId: session.user.tenantId,
      userId: session.user.id,
      email: session.user.email,
    }
    saveConfig(config)
    logSuccess(`Authenticated as ${session.user.email}`)
    logSuccess("Cloud CLI credentials saved securely")
    return config
  } finally {
    await callback.close()
  }
}

/**
 * Current browser identity-provider adapter.
 */
export const clerkAuthProvider: CliAuthProvider = {
  id: "clerk",
  login: browserLoginCommand,
}

/**
 * Waits for an OAuth callback on an ephemeral loopback port.
 *
 * @param expectedState - State value generated by the CLI.
 * @returns Callback result, redirect URI, and server cleanup.
 */
async function startCallbackServer(expectedState: string): Promise<{
  redirectUri: string
  result: Promise<BrowserCallback>
  close: () => Promise<void>
}> {
  let resolveResult: (value: BrowserCallback) => void = () => undefined
  let rejectResult: (reason?: unknown) => void = () => undefined
  const result = new Promise<BrowserCallback>((resolve, reject) => {
    resolveResult = resolve
    rejectResult = reject
  })
  const server = createServer((request, response) => {
    handleCallbackRequest(request, response, expectedState, resolveResult, rejectResult)
  })
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject)
    server.listen(0, "127.0.0.1", resolve)
  })
  const address = server.address()
  if (!address || typeof address === "string") {
    await closeServer(server)
    throw new Error("Unable to bind the CLI callback listener")
  }
  const redirectUri = `http://127.0.0.1:${address.port}${CALLBACK_PATH}`
  const timeout = setTimeout(() => {
    rejectResult(new Error("Timed out waiting for browser authentication"))
  }, CALLBACK_TIMEOUT_MS)
  result.finally(() => clearTimeout(timeout)).catch(() => undefined)

  return {
    redirectUri,
    result,
    close: () => closeServer(server),
  }
}

function handleCallbackRequest(
  request: IncomingMessage,
  response: ServerResponse,
  expectedState: string,
  resolveResult: (value: BrowserCallback) => void,
  rejectResult: (reason?: unknown) => void,
): void {
  const requestUrl = new URL(request.url ?? "/", "http://127.0.0.1")
  if (requestUrl.pathname !== CALLBACK_PATH) {
    response.writeHead(404).end()
    return
  }
  const code = requestUrl.searchParams.get("code")
  const state = requestUrl.searchParams.get("state")
  const error = requestUrl.searchParams.get("error")
  if (error) {
    response.writeHead(400, { "Content-Type": "text/html" })
    response.end("<h1>Limetry CLI authorization failed</h1><p>You can close this window.</p>")
    rejectResult(new Error(`Browser authorization failed: ${error}`))
    return
  }
  if (!code || !state || state !== expectedState) {
    response.writeHead(400, { "Content-Type": "text/html" })
    response.end("<h1>Invalid Limetry CLI callback</h1><p>You can close this window.</p>")
    rejectResult(new Error("Invalid browser authentication state"))
    return
  }
  response.writeHead(200, { "Content-Type": "text/html" })
  response.end("<h1>Limetry CLI connected</h1><p>You can close this window.</p>")
  resolveResult({ code, state })
}

function closeServer(server: ReturnType<typeof createServer>): Promise<void> {
  return new Promise((resolve) => {
    server.close(() => resolve())
  })
}
