// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BranchBackupSchedule extends pulumi.CustomResource {
    /**
     * Get an existing BranchBackupSchedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BranchBackupScheduleState, opts?: pulumi.CustomResourceOptions): BranchBackupSchedule {
        return new BranchBackupSchedule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'neon:index/branchBackupSchedule:BranchBackupSchedule';

    /**
     * Returns true if the given object is an instance of BranchBackupSchedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BranchBackupSchedule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BranchBackupSchedule.__pulumiType;
    }

    /**
     * The Neon branch ID.
     */
    declare public readonly branchId: pulumi.Output<string>;
    /**
     * The Neon project ID.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Snapshot frequencies configured for the branch.
     */
    declare public readonly schedules: pulumi.Output<outputs.BranchBackupScheduleSchedule[]>;

    /**
     * Create a BranchBackupSchedule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BranchBackupScheduleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BranchBackupScheduleArgs | BranchBackupScheduleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BranchBackupScheduleState | undefined;
            resourceInputs["branchId"] = state?.branchId;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["schedules"] = state?.schedules;
        } else {
            const args = argsOrState as BranchBackupScheduleArgs | undefined;
            if (args?.branchId === undefined && !opts.urn) {
                throw new Error("Missing required property 'branchId'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.schedules === undefined && !opts.urn) {
                throw new Error("Missing required property 'schedules'");
            }
            resourceInputs["branchId"] = args?.branchId;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["schedules"] = args?.schedules;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BranchBackupSchedule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BranchBackupSchedule resources.
 */
export interface BranchBackupScheduleState {
    /**
     * The Neon branch ID.
     */
    branchId?: pulumi.Input<string | undefined>;
    /**
     * The Neon project ID.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Snapshot frequencies configured for the branch.
     */
    schedules?: pulumi.Input<pulumi.Input<inputs.BranchBackupScheduleSchedule>[] | undefined>;
}

/**
 * The set of arguments for constructing a BranchBackupSchedule resource.
 */
export interface BranchBackupScheduleArgs {
    /**
     * The Neon branch ID.
     */
    branchId: pulumi.Input<string>;
    /**
     * The Neon project ID.
     */
    projectId: pulumi.Input<string>;
    /**
     * Snapshot frequencies configured for the branch.
     */
    schedules: pulumi.Input<pulumi.Input<inputs.BranchBackupScheduleSchedule>[]>;
}
